# -*- coding: utf-8 -*-
"""week4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRuYsUGoglimIKZyp48oiwZSlUak3-gQ
"""

import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings('ignore')

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("IMDB Dataset.csv")

df.head()

df.shape

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

stop_words = set(stopwords.words('english'))
def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)
    df['clean_review'] = df['review'].apply(clean_text)

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

df['clean_review'] = df['review'].apply(clean_text)

df[['review','clean_review']].head()

X = vectorizer.fit_transform(df['clean_review'])
y = df['sentiment']

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df['clean_review'])

y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = MultinomialNB()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

sample_review = [
    "This movie was amazing and fantastic"
]

sample_vector = vectorizer.transform(sample_review)

prediction = model.predict(sample_vector)

print(prediction)

sample_review = [
    "This movie was terrible, boring, awful and a complete waste of time"
]

sample_vector = vectorizer.transform(sample_review)

prediction = model.predict(sample_vector)

print(prediction)